# -*- coding: utf-8 -*-
"""rondom_forest_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHV3BKq-YDElh0R7DtYUFufHcZItBBY3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Import the Iris dataset
from sklearn.datasets import load_iris
dataset = load_iris()

dataset.target_names

dataset.feature_names

dataset.data

X = dataset.data
y = dataset.target

# Splitting the data into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Fitting the classifier to the training set
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state = 0)
model.fit(X_train, y_train)

# Predicting the test set result
y_pred = model.predict(X_test)

# Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

# Getting the score for our model
model.score(X_test, y_test)

